name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Test packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        shell: bash
        run: |
          yarn install --immutable

      - name: Build and validate packages
        run: |
          yarn workspaces foreach -t run build

      - name: Run all tests
        run: |
          yarn test
